spring:
  application:
    name: ADMIN-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ust

server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    instanceId: ${spring.application.name}:${random.value}